---
apiVersion: apps/v1           
kind: Deployment              
metadata:
  name: polling-app-server     
  labels:                     
    app: polling-app-server
spec:
  replicas: 1                 
  selector:
    matchLabels:               
      app: polling-app-server
  template:                    
    metadata:
      labels:                 
        app: polling-app-server
    spec:                     
      containers:
      - name: polling-app-server
        image: apgonzalesf/hero-backend:1.0
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080  
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:                   
        - name: POSTGRES_USER  
          valueFrom:         
            secretKeyRef:
              name: postgres-user-pass
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-user-pass
              key: password
        - name: DB_SERVER
          valueFrom:
            secretKeyRef:
              name: postgres-db-url
              key: url
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-db-url
              key: database      
---
apiVersion: v1                 
kind: Service                  
metadata:                     
  name: polling-app-server     
  labels:                    
    app: polling-app-server
spec:                         
  type: NodePort   
  selector:
    app: polling-app-server    
  ports:       
  - name: http
    port: 8080
    targetPort: 8080